-- ============================================================================
-- NexaFarma - Esquema inicial de base de datos (PostgreSQL / Supabase)
-- Generado a partir de las 19 entidades JPA del repositorio Dinamo-mrm/NexaFarma
-- (com.nexafarma.entity), respetando nombres de tabla, columnas, tipos,
-- restricciones NOT NULL/UNIQUE y valores por defecto definidos en el codigo.
--
-- Uso:
--   1) Supabase SQL Editor: pegar y ejecutar directamente.
--   2) Flyway: guardar como src/main/resources/db/migration/V1__esquema_inicial_nexafarma.sql
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. roles
-- ----------------------------------------------------------------------------
CREATE TABLE roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(30) NOT NULL,
    descripcion  VARCHAR(255),
    CONSTRAINT uk_roles_nombre UNIQUE (nombre),
    CONSTRAINT ck_roles_nombre CHECK (nombre IN ('ADMINISTRADOR','FARMACEUTICO','VENDEDOR','AUXILIAR'))
);

-- ----------------------------------------------------------------------------
-- 2. empleados
-- ----------------------------------------------------------------------------
CREATE TABLE empleados (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento        VARCHAR(20)  NOT NULL,
    nombre_completo  VARCHAR(150) NOT NULL,
    correo           VARCHAR(150),
    telefono         VARCHAR(20),
    direccion        VARCHAR(200),
    cargo            VARCHAR(80)  NOT NULL,
    salario          NUMERIC(12,2) CHECK (salario >= 0),
    activo           BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_ingreso    DATE,
    creado_en        TIMESTAMP,
    actualizado_en   TIMESTAMP,
    CONSTRAINT uk_empleados_documento UNIQUE (documento)
);

-- ----------------------------------------------------------------------------
-- 3. usuarios (1 a 1 con empleados)
-- ----------------------------------------------------------------------------
CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(60) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    empleado_id    BIGINT NOT NULL,
    rol_id         BIGINT NOT NULL,
    activo         BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_acceso  TIMESTAMP,
    creado_en      TIMESTAMP,
    CONSTRAINT uk_usuarios_username UNIQUE (username),
    CONSTRAINT uk_usuarios_empleado_id UNIQUE (empleado_id),
    CONSTRAINT fk_usuarios_empleado FOREIGN KEY (empleado_id) REFERENCES empleados (id),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES roles (id)
);

-- ----------------------------------------------------------------------------
-- 4. clientes
-- ----------------------------------------------------------------------------
CREATE TABLE clientes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento          VARCHAR(20)  NOT NULL,
    nombre_completo    VARCHAR(150) NOT NULL,
    telefono           VARCHAR(20),
    correo             VARCHAR(150),
    direccion          VARCHAR(200),
    fecha_nacimiento   DATE,
    eps                VARCHAR(100),
    alergias           VARCHAR(500),
    activo             BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en          TIMESTAMP,
    actualizado_en     TIMESTAMP,
    CONSTRAINT uk_clientes_documento UNIQUE (documento)
);

-- ----------------------------------------------------------------------------
-- 5. proveedores
-- ----------------------------------------------------------------------------
CREATE TABLE proveedores (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nit               VARCHAR(20)  NOT NULL,
    razon_social      VARCHAR(150) NOT NULL,
    nombre_contacto   VARCHAR(150),
    telefono          VARCHAR(20),
    correo            VARCHAR(150),
    direccion         VARCHAR(200),
    activo            BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_proveedores_nit UNIQUE (nit)
);

-- ----------------------------------------------------------------------------
-- 6. categorias
-- ----------------------------------------------------------------------------
CREATE TABLE categorias (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  VARCHAR(255),
    CONSTRAINT uk_categorias_nombre UNIQUE (nombre)
);

-- ----------------------------------------------------------------------------
-- 7. productos (superclase abstracta, estrategia JOINED)
-- ----------------------------------------------------------------------------
CREATE TABLE productos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_interno   VARCHAR(30)  NOT NULL,
    codigo_barras    VARCHAR(50)  NOT NULL,
    nombre_comercial VARCHAR(200) NOT NULL,
    descripcion      VARCHAR(500),
    presentacion     VARCHAR(80),
    categoria_id     BIGINT NOT NULL,
    proveedor_id     BIGINT NOT NULL,
    precio_compra    NUMERIC(12,2) NOT NULL CHECK (precio_compra >= 0.01),
    precio_venta     NUMERIC(12,2) NOT NULL CHECK (precio_venta >= 0.01),
    stock_minimo     INTEGER NOT NULL DEFAULT 10,
    ubicacion        VARCHAR(100),
    activo           BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_productos_codigo_interno UNIQUE (codigo_interno),
    CONSTRAINT uk_productos_codigo_barras UNIQUE (codigo_barras),
    CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT fk_productos_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id)
);

-- ----------------------------------------------------------------------------
-- 8. medicamentos (subclase de productos, JOINED -> mismo id/PK que productos)
-- ----------------------------------------------------------------------------
CREATE TABLE medicamentos (
    id                       BIGINT PRIMARY KEY,
    nombre_generico          VARCHAR(200),
    concentracion            VARCHAR(100),
    laboratorio_fabricante   VARCHAR(150),
    registro_invima          VARCHAR(50) NOT NULL,
    venta_libre              BOOLEAN NOT NULL DEFAULT TRUE,
    requiere_formula         BOOLEAN NOT NULL DEFAULT FALSE,
    uso_controlado           BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_refrigeracion   BOOLEAN NOT NULL DEFAULT FALSE,
    tiene_restricciones      BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_medicamentos_producto FOREIGN KEY (id) REFERENCES productos (id)
);

-- ----------------------------------------------------------------------------
-- 9. lotes
-- ----------------------------------------------------------------------------
CREATE TABLE lotes (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicamento_id         BIGINT NOT NULL,
    numero_lote            VARCHAR(50) NOT NULL,
    fecha_fabricacion      DATE NOT NULL,
    fecha_vencimiento      DATE NOT NULL,
    cantidad_disponible    INTEGER NOT NULL CHECK (cantidad_disponible >= 0),
    estado                 VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    devuelto_a_proveedor   BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_lotes_medicamento_numero UNIQUE (medicamento_id, numero_lote),
    CONSTRAINT ck_lotes_estado CHECK (estado IN ('ACTIVO','VENCIDO','RETIRADO')),
    CONSTRAINT fk_lotes_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id)
);

-- ----------------------------------------------------------------------------
-- 10. inventario (existencia agregada por medicamento)
-- ----------------------------------------------------------------------------
CREATE TABLE inventario (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicamento_id         BIGINT NOT NULL,
    cantidad_disponible    INTEGER NOT NULL DEFAULT 0,
    stock_minimo           INTEGER NOT NULL DEFAULT 10,
    ultima_actualizacion   TIMESTAMP,
    CONSTRAINT uk_inventario_medicamento UNIQUE (medicamento_id),
    CONSTRAINT fk_inventario_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id)
);

-- ----------------------------------------------------------------------------
-- 11. movimientos_inventario (auditoria)
-- ----------------------------------------------------------------------------
CREATE TABLE movimientos_inventario (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicamento_id           BIGINT NOT NULL,
    tipo_movimiento          VARCHAR(20) NOT NULL,
    cantidad                 INTEGER NOT NULL,
    fecha                    TIMESTAMP NOT NULL,
    usuario_responsable_id   BIGINT NOT NULL,
    motivo                   VARCHAR(255),
    existencia_anterior      INTEGER NOT NULL,
    nueva_existencia         INTEGER NOT NULL,
    CONSTRAINT ck_mov_inv_tipo CHECK (tipo_movimiento IN ('ENTRADA','SALIDA','AJUSTE')),
    CONSTRAINT fk_mov_inv_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id),
    CONSTRAINT fk_mov_inv_empleado FOREIGN KEY (usuario_responsable_id) REFERENCES empleados (id)
);

-- ----------------------------------------------------------------------------
-- 12. compras
-- ----------------------------------------------------------------------------
CREATE TABLE compras (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_compra            VARCHAR(30) NOT NULL,
    proveedor_id             BIGINT NOT NULL,
    empleado_responsable_id  BIGINT NOT NULL,
    fecha_compra             TIMESTAMP NOT NULL,
    subtotal                 NUMERIC(12,2) NOT NULL,
    impuestos                NUMERIC(12,2) NOT NULL,
    total                    NUMERIC(12,2) NOT NULL,
    forma_pago               VARCHAR(25) NOT NULL,
    estado                   VARCHAR(25) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT uk_compras_numero UNIQUE (numero_compra),
    CONSTRAINT ck_compras_forma_pago CHECK (forma_pago IN
        ('EFECTIVO','TARJETA_DEBITO','TARJETA_CREDITO','TRANSFERENCIA','PAGO_ELECTRONICO','PAGO_MIXTO')),
    CONSTRAINT ck_compras_estado CHECK (estado IN
        ('PENDIENTE','RECIBIDA','PARCIALMENTE_RECIBIDA','CANCELADA','DEVUELTA')),
    CONSTRAINT fk_compras_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
    CONSTRAINT fk_compras_empleado FOREIGN KEY (empleado_responsable_id) REFERENCES empleados (id)
);

-- ----------------------------------------------------------------------------
-- 13. detalle_compras
-- ----------------------------------------------------------------------------
CREATE TABLE detalle_compras (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id         BIGINT NOT NULL,
    medicamento_id    BIGINT NOT NULL,
    cantidad          INTEGER NOT NULL CHECK (cantidad >= 1),
    precio_unitario   NUMERIC(12,2) NOT NULL,
    subtotal          NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_detalle_compras_compra FOREIGN KEY (compra_id) REFERENCES compras (id),
    CONSTRAINT fk_detalle_compras_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id)
);

-- ----------------------------------------------------------------------------
-- 14. ventas
-- ----------------------------------------------------------------------------
CREATE TABLE ventas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_venta   VARCHAR(30) NOT NULL,
    cliente_id     BIGINT NOT NULL,
    empleado_id    BIGINT NOT NULL,
    fecha          TIMESTAMP NOT NULL,
    subtotal       NUMERIC(12,2) NOT NULL,
    descuento      NUMERIC(12,2) NOT NULL DEFAULT 0,
    impuestos      NUMERIC(12,2) NOT NULL,
    total          NUMERIC(12,2) NOT NULL,
    metodo_pago    VARCHAR(25) NOT NULL,
    estado         VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT uk_ventas_numero UNIQUE (numero_venta),
    CONSTRAINT ck_ventas_metodo_pago CHECK (metodo_pago IN
        ('EFECTIVO','TARJETA_DEBITO','TARJETA_CREDITO','TRANSFERENCIA','PAGO_ELECTRONICO','PAGO_MIXTO')),
    CONSTRAINT ck_ventas_estado CHECK (estado IN ('PENDIENTE','PAGADA','ANULADA','DEVUELTA')),
    CONSTRAINT fk_ventas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_ventas_empleado FOREIGN KEY (empleado_id) REFERENCES empleados (id)
);

-- ----------------------------------------------------------------------------
-- 15. detalle_ventas
-- ----------------------------------------------------------------------------
CREATE TABLE detalle_ventas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id          BIGINT NOT NULL,
    medicamento_id    BIGINT NOT NULL,
    lote_id           BIGINT,
    cantidad          INTEGER NOT NULL CHECK (cantidad >= 1),
    precio_unitario   NUMERIC(12,2) NOT NULL,
    subtotal          NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_detalle_ventas_venta FOREIGN KEY (venta_id) REFERENCES ventas (id),
    CONSTRAINT fk_detalle_ventas_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id),
    CONSTRAINT fk_detalle_ventas_lote FOREIGN KEY (lote_id) REFERENCES lotes (id)
);

-- ----------------------------------------------------------------------------
-- 16. formulas_medicas
-- ----------------------------------------------------------------------------
CREATE TABLE formulas_medicas (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id                     BIGINT NOT NULL,
    nombre_medico                  VARCHAR(150) NOT NULL,
    numero_tarjeta_profesional     VARCHAR(50) NOT NULL,
    entidad_salud                  VARCHAR(150),
    fecha_expedicion               DATE NOT NULL,
    duracion_tratamiento_dias      INTEGER,
    archivo_adjunto_url            VARCHAR(500),
    CONSTRAINT fk_formulas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

-- ----------------------------------------------------------------------------
-- 17. detalle_formulas
-- ----------------------------------------------------------------------------
CREATE TABLE detalle_formulas (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formula_medica_id       BIGINT NOT NULL,
    medicamento_id          BIGINT NOT NULL,
    dosis                   VARCHAR(100),
    frecuencia              VARCHAR(100),
    duracion_tratamiento    VARCHAR(100),
    CONSTRAINT fk_detalle_formulas_formula FOREIGN KEY (formula_medica_id) REFERENCES formulas_medicas (id),
    CONSTRAINT fk_detalle_formulas_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id)
);

-- ----------------------------------------------------------------------------
-- 18. devoluciones
-- ----------------------------------------------------------------------------
CREATE TABLE devoluciones (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                          VARCHAR(15) NOT NULL,
    venta_origen_id               BIGINT,
    compra_origen_id              BIGINT,
    medicamento_id                BIGINT NOT NULL,
    cantidad                      INTEGER NOT NULL CHECK (cantidad >= 1),
    motivo                        VARCHAR(30) NOT NULL,
    estado_producto               VARCHAR(100),
    validado_por_farmaceutico     BOOLEAN NOT NULL DEFAULT FALSE,
    validado_por_id               BIGINT,
    fecha                         TIMESTAMP NOT NULL,
    CONSTRAINT ck_devoluciones_tipo CHECK (tipo IN ('CLIENTE','PROVEEDOR')),
    CONSTRAINT ck_devoluciones_motivo CHECK (motivo IN
        ('PRODUCTO_DEFECTUOSO','ERROR_EN_LA_ENTREGA','PRODUCTO_PROXIMO_A_VENCER',
         'PRODUCTO_VENCIDO','RETIRO_DEL_MERCADO','DANO_EN_EL_EMPAQUE','ERROR_DEL_PROVEEDOR')),
    CONSTRAINT fk_devoluciones_venta FOREIGN KEY (venta_origen_id) REFERENCES ventas (id),
    CONSTRAINT fk_devoluciones_compra FOREIGN KEY (compra_origen_id) REFERENCES compras (id),
    CONSTRAINT fk_devoluciones_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos (id),
    CONSTRAINT fk_devoluciones_validado_por FOREIGN KEY (validado_por_id) REFERENCES empleados (id)
);

-- ----------------------------------------------------------------------------
-- 19. domicilios
-- ----------------------------------------------------------------------------
CREATE TABLE domicilios (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id              BIGINT NOT NULL,
    cliente_id            BIGINT NOT NULL,
    direccion_entrega     VARCHAR(200) NOT NULL,
    telefono_contacto     VARCHAR(20),
    domiciliario_id       BIGINT,
    valor_domicilio       NUMERIC(12,2),
    estado                VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    hora_salida           TIMESTAMP,
    hora_entrega          TIMESTAMP,
    CONSTRAINT ck_domicilios_estado CHECK (estado IN
        ('PENDIENTE','EN_PREPARACION','EN_CAMINO','ENTREGADO','CANCELADO')),
    CONSTRAINT fk_domicilios_venta FOREIGN KEY (venta_id) REFERENCES ventas (id),
    CONSTRAINT fk_domicilios_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_domicilios_domiciliario FOREIGN KEY (domiciliario_id) REFERENCES empleados (id)
);

-- ============================================================================
-- Indices adicionales recomendados (no generados por Hibernate automaticamente,
-- pero utiles para las consultas de negocio: alertas de stock, FEFO, reportes)
-- ============================================================================
CREATE INDEX idx_lotes_fecha_vencimiento ON lotes (fecha_vencimiento);
CREATE INDEX idx_lotes_medicamento_estado ON lotes (medicamento_id, estado);
CREATE INDEX idx_ventas_fecha ON ventas (fecha);
CREATE INDEX idx_ventas_cliente ON ventas (cliente_id);
CREATE INDEX idx_compras_fecha ON compras (fecha_compra);
CREATE INDEX idx_mov_inv_medicamento_fecha ON movimientos_inventario (medicamento_id, fecha);
CREATE INDEX idx_formulas_cliente ON formulas_medicas (cliente_id);
CREATE INDEX idx_domicilios_estado ON domicilios (estado);

COMMIT;

-- ============================================================================
-- NOTA sobre Supabase y Row Level Security (RLS):
-- Estas tablas quedan SIN RLS habilitado (equivalente a como se comportan en
-- MySQL: sin control de fila). Esto es correcto si la app Spring Boot se
-- conecta por JDBC directo con sus propias credenciales de Postgres.
-- Si en algun momento se expone alguna tabla via la API automatica de
-- Supabase (PostgREST) a clientes que no sean el backend Spring Boot,
-- se debera habilitar RLS y definir politicas antes de eso, por ejemplo:
--   ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
-- ============================================================================
